application:
  descriptiveName: ${nais.app.name}
  name: ${nais.app.name}
  version: ${nais.app.image}

spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: oracle.jdbc.OracleDriver

srvtps:
  forvalteren:
    username: ${TPSF_CREDENTIAL_USERNAME}
    password: ${TPSF_CREDENTIAL_PASSWORD}