name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - uses: actions/setup-node@v1
        name: Set up Node 10
        with:
          node-version: '10'
      - name: Compile with Maven
        working-directory: tps-forvalteren-provider/tps-forvalteren-provider-web/src/main/web-src
        run: npm install